spring.application.name=config-server
server.port=8888

# Remote Git configuration
spring.cloud.config.server.git.uri=https://github.com/JomainaAhmed/config-repo1
spring.cloud.config.server.git.clone-on-start=true

# Local native profile configuration (Commented out)
# spring.profiles.active=native
# spring.cloud.config.server.native.search-locations=classpath:/config
square.token=squ_30b8896d2d5f6c23c7667d1911ec8145d5dbfe03